// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: usedservice/usedservice.proto

package usedservice

import (
	context "context"
	encoding_binary "encoding/binary"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	service "github.com/nekizz/final-project/backend/go-pbtype/service"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type UsedService struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity             int32            `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	TotalAmount          float32          `protobuf:"fixed32,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Price                float32          `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	ServiceId            string           `protobuf:"bytes,5,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	BookedRoomId         string           `protobuf:"bytes,6,opt,name=booked_room_id,json=bookedRoomId,proto3" json:"booked_room_id,omitempty"`
	Service              *service.Service `protobuf:"bytes,7,opt,name=service,proto3" json:"service,omitempty"`
	CreatedAt            string           `protobuf:"bytes,20,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string           `protobuf:"bytes,21,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *UsedService) Reset()         { *m = UsedService{} }
func (m *UsedService) String() string { return proto.CompactTextString(m) }
func (*UsedService) ProtoMessage()    {}
func (*UsedService) Descriptor() ([]byte, []int) {
	return fileDescriptor_2080e5dd4a310055, []int{0}
}
func (m *UsedService) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UsedService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UsedService.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UsedService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsedService.Merge(m, src)
}
func (m *UsedService) XXX_Size() int {
	return m.Size()
}
func (m *UsedService) XXX_DiscardUnknown() {
	xxx_messageInfo_UsedService.DiscardUnknown(m)
}

var xxx_messageInfo_UsedService proto.InternalMessageInfo

func (m *UsedService) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UsedService) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *UsedService) GetTotalAmount() float32 {
	if m != nil {
		return m.TotalAmount
	}
	return 0
}

func (m *UsedService) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *UsedService) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}

func (m *UsedService) GetBookedRoomId() string {
	if m != nil {
		return m.BookedRoomId
	}
	return ""
}

func (m *UsedService) GetService() *service.Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *UsedService) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *UsedService) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (*UsedService) XXX_MessageName() string {
	return "usedservice.UsedService"
}

type OneUsedServiceRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OneUsedServiceRequest) Reset()         { *m = OneUsedServiceRequest{} }
func (m *OneUsedServiceRequest) String() string { return proto.CompactTextString(m) }
func (*OneUsedServiceRequest) ProtoMessage()    {}
func (*OneUsedServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2080e5dd4a310055, []int{1}
}
func (m *OneUsedServiceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OneUsedServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OneUsedServiceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OneUsedServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OneUsedServiceRequest.Merge(m, src)
}
func (m *OneUsedServiceRequest) XXX_Size() int {
	return m.Size()
}
func (m *OneUsedServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OneUsedServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OneUsedServiceRequest proto.InternalMessageInfo

func (m *OneUsedServiceRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (*OneUsedServiceRequest) XXX_MessageName() string {
	return "usedservice.OneUsedServiceRequest"
}

type ListUsedServiceRequest struct {
	Page                 uint32   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit                uint32   `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	CreatedAtMin         string   `protobuf:"bytes,5,opt,name=created_at_min,json=createdAtMin,proto3" json:"created_at_min,omitempty"`
	CreatedAtMax         string   `protobuf:"bytes,6,opt,name=created_at_max,json=createdAtMax,proto3" json:"created_at_max,omitempty"`
	SearchField          string   `protobuf:"bytes,7,opt,name=search_field,json=searchField,proto3" json:"search_field,omitempty"`
	SearchValue          string   `protobuf:"bytes,8,opt,name=search_value,json=searchValue,proto3" json:"search_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsedServiceRequest) Reset()         { *m = ListUsedServiceRequest{} }
func (m *ListUsedServiceRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsedServiceRequest) ProtoMessage()    {}
func (*ListUsedServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2080e5dd4a310055, []int{2}
}
func (m *ListUsedServiceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListUsedServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListUsedServiceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListUsedServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsedServiceRequest.Merge(m, src)
}
func (m *ListUsedServiceRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListUsedServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsedServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsedServiceRequest proto.InternalMessageInfo

func (m *ListUsedServiceRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListUsedServiceRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListUsedServiceRequest) GetCreatedAtMin() string {
	if m != nil {
		return m.CreatedAtMin
	}
	return ""
}

func (m *ListUsedServiceRequest) GetCreatedAtMax() string {
	if m != nil {
		return m.CreatedAtMax
	}
	return ""
}

func (m *ListUsedServiceRequest) GetSearchField() string {
	if m != nil {
		return m.SearchField
	}
	return ""
}

func (m *ListUsedServiceRequest) GetSearchValue() string {
	if m != nil {
		return m.SearchValue
	}
	return ""
}

func (*ListUsedServiceRequest) XXX_MessageName() string {
	return "usedservice.ListUsedServiceRequest"
}

type ListUsedServiceResponse struct {
	Items                []*UsedService `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	MaxPage              uint32         `protobuf:"varint,2,opt,name=max_page,json=maxPage,proto3" json:"max_page,omitempty"`
	TotalCount           uint32         `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page                 uint32         `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit                uint32         `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	SearchField          string         `protobuf:"bytes,6,opt,name=search_field,json=searchField,proto3" json:"search_field,omitempty"`
	SearchValue          string         `protobuf:"bytes,7,opt,name=search_value,json=searchValue,proto3" json:"search_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListUsedServiceResponse) Reset()         { *m = ListUsedServiceResponse{} }
func (m *ListUsedServiceResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsedServiceResponse) ProtoMessage()    {}
func (*ListUsedServiceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2080e5dd4a310055, []int{3}
}
func (m *ListUsedServiceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListUsedServiceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListUsedServiceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListUsedServiceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsedServiceResponse.Merge(m, src)
}
func (m *ListUsedServiceResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListUsedServiceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsedServiceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsedServiceResponse proto.InternalMessageInfo

func (m *ListUsedServiceResponse) GetItems() []*UsedService {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ListUsedServiceResponse) GetMaxPage() uint32 {
	if m != nil {
		return m.MaxPage
	}
	return 0
}

func (m *ListUsedServiceResponse) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *ListUsedServiceResponse) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListUsedServiceResponse) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListUsedServiceResponse) GetSearchField() string {
	if m != nil {
		return m.SearchField
	}
	return ""
}

func (m *ListUsedServiceResponse) GetSearchValue() string {
	if m != nil {
		return m.SearchValue
	}
	return ""
}

func (*ListUsedServiceResponse) XXX_MessageName() string {
	return "usedservice.ListUsedServiceResponse"
}
func init() {
	proto.RegisterType((*UsedService)(nil), "usedservice.UsedService")
	golang_proto.RegisterType((*UsedService)(nil), "usedservice.UsedService")
	proto.RegisterType((*OneUsedServiceRequest)(nil), "usedservice.OneUsedServiceRequest")
	golang_proto.RegisterType((*OneUsedServiceRequest)(nil), "usedservice.OneUsedServiceRequest")
	proto.RegisterType((*ListUsedServiceRequest)(nil), "usedservice.ListUsedServiceRequest")
	golang_proto.RegisterType((*ListUsedServiceRequest)(nil), "usedservice.ListUsedServiceRequest")
	proto.RegisterType((*ListUsedServiceResponse)(nil), "usedservice.ListUsedServiceResponse")
	golang_proto.RegisterType((*ListUsedServiceResponse)(nil), "usedservice.ListUsedServiceResponse")
}

func init() { proto.RegisterFile("usedservice/usedservice.proto", fileDescriptor_2080e5dd4a310055) }
func init() {
	golang_proto.RegisterFile("usedservice/usedservice.proto", fileDescriptor_2080e5dd4a310055)
}

var fileDescriptor_2080e5dd4a310055 = []byte{
	// 710 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x4e, 0xd4, 0x40,
	0x14, 0xce, 0xec, 0x2f, 0xcc, 0xb2, 0x84, 0x4c, 0xf8, 0xa9, 0x55, 0xd6, 0xb5, 0x92, 0xb8, 0x21,
	0xd9, 0x36, 0xc1, 0x3b, 0x13, 0x2f, 0x10, 0x95, 0x90, 0x68, 0x34, 0x25, 0x70, 0xa1, 0x17, 0x75,
	0xb6, 0x3d, 0x94, 0x91, 0xb6, 0x53, 0xda, 0x29, 0x59, 0x30, 0xde, 0xf8, 0x0a, 0x3e, 0x81, 0x6f,
	0xe2, 0x25, 0x97, 0x26, 0xfa, 0x00, 0x06, 0x7c, 0x05, 0xe3, 0xad, 0xe9, 0xb4, 0x85, 0x2e, 0x2c,
	0xf8, 0x73, 0xd7, 0xf9, 0xce, 0x77, 0xe6, 0x9c, 0xef, 0xeb, 0x99, 0x83, 0x17, 0x93, 0x18, 0x9c,
	0x18, 0xa2, 0x03, 0x66, 0x83, 0x51, 0xfa, 0xd6, 0xc3, 0x88, 0x0b, 0x4e, 0x5a, 0x25, 0x48, 0xed,
	0xbb, 0x4c, 0xec, 0x26, 0x03, 0xdd, 0xe6, 0xbe, 0xe1, 0x72, 0x97, 0x1b, 0x92, 0x33, 0x48, 0x76,
	0xe4, 0x49, 0x1e, 0xe4, 0x57, 0x96, 0xab, 0xde, 0x74, 0x39, 0x77, 0x3d, 0x38, 0x67, 0x81, 0x1f,
	0x8a, 0xc3, 0x3c, 0x78, 0x2b, 0x0f, 0xd2, 0x90, 0x19, 0x34, 0x08, 0xb8, 0xa0, 0x82, 0xf1, 0x20,
	0xce, 0xa3, 0xeb, 0xa5, 0x4a, 0x01, 0xec, 0xb1, 0xa3, 0x23, 0x63, 0x87, 0x05, 0xd4, 0xeb, 0x87,
	0x11, 0x7f, 0x0b, 0xb6, 0x30, 0x06, 0xd4, 0xde, 0x83, 0xc0, 0x31, 0x5c, 0xde, 0x0f, 0x07, 0xe2,
	0x30, 0x04, 0xa3, 0xd0, 0x30, 0xd2, 0xbf, 0xf6, 0xa9, 0x82, 0x5b, 0x5b, 0x31, 0x38, 0x9b, 0x19,
	0x4a, 0xa6, 0x71, 0x85, 0x39, 0x0a, 0xea, 0xa2, 0xde, 0xa4, 0x59, 0x61, 0x0e, 0x51, 0xf1, 0xc4,
	0x7e, 0x42, 0x03, 0xc1, 0xc4, 0xa1, 0x52, 0xe9, 0xa2, 0x5e, 0xdd, 0x3c, 0x3b, 0x93, 0x3b, 0x78,
	0x4a, 0x70, 0x41, 0x3d, 0x8b, 0xfa, 0x3c, 0x09, 0x84, 0x52, 0xed, 0xa2, 0x5e, 0xc5, 0x6c, 0x49,
	0x6c, 0x55, 0x42, 0x64, 0x16, 0xd7, 0xc3, 0x88, 0xd9, 0xa0, 0xd4, 0x64, 0x2c, 0x3b, 0x90, 0x45,
	0x8c, 0xf3, 0x2e, 0x2c, 0xe6, 0x28, 0x75, 0x59, 0x6c, 0x32, 0x47, 0x36, 0x1c, 0xb2, 0x84, 0xa7,
	0x07, 0x9c, 0xef, 0x81, 0x63, 0x45, 0x9c, 0xfb, 0x29, 0xa5, 0x21, 0x29, 0x53, 0x19, 0x6a, 0x72,
	0xee, 0x6f, 0x38, 0x64, 0x19, 0x37, 0xf3, 0x14, 0xa5, 0xd9, 0x45, 0xbd, 0xd6, 0xca, 0x8c, 0x5e,
	0x48, 0xcb, 0xc5, 0x98, 0x05, 0x21, 0x2d, 0x68, 0x47, 0x40, 0x05, 0x38, 0x16, 0x15, 0xca, 0x6c,
	0x56, 0x30, 0x47, 0x56, 0x45, 0x1a, 0x4e, 0x42, 0xa7, 0x08, 0xcf, 0x65, 0xe1, 0x1c, 0x59, 0x15,
	0xda, 0x3d, 0x3c, 0xf7, 0x22, 0x80, 0x92, 0x4b, 0x26, 0xec, 0x27, 0x10, 0x8b, 0x8b, 0x66, 0x69,
	0xdf, 0x10, 0x9e, 0x7f, 0xc6, 0x62, 0x31, 0x86, 0x4a, 0x70, 0x2d, 0xa4, 0x2e, 0x48, 0x8f, 0xda,
	0xa6, 0xfc, 0x4e, 0xcd, 0xf1, 0x98, 0xcf, 0x84, 0x34, 0xa7, 0x6d, 0x66, 0x87, 0x54, 0xfd, 0x79,
	0xaf, 0x96, 0xcf, 0x82, 0xdc, 0xa0, 0xa9, 0xb3, 0x7e, 0x9f, 0xb3, 0xe0, 0x22, 0x8b, 0x0e, 0x0b,
	0x8f, 0xce, 0x59, 0x74, 0x98, 0xfe, 0xa1, 0x18, 0x68, 0x64, 0xef, 0x5a, 0x3b, 0x0c, 0x3c, 0x47,
	0x1a, 0x35, 0x69, 0xb6, 0x32, 0xec, 0x69, 0x0a, 0x95, 0x28, 0x07, 0xd4, 0x4b, 0x40, 0x99, 0x28,
	0x53, 0xb6, 0x53, 0x48, 0xfb, 0x89, 0xf0, 0xc2, 0x25, 0x59, 0x71, 0xc8, 0x83, 0x18, 0x88, 0x8e,
	0xeb, 0x4c, 0x80, 0x1f, 0x2b, 0xa8, 0x5b, 0xed, 0xb5, 0x56, 0x14, 0xbd, 0xfc, 0x44, 0xca, 0x09,
	0x19, 0x8d, 0xdc, 0xc0, 0x13, 0x3e, 0x1d, 0x5a, 0xd2, 0x8b, 0x8a, 0x94, 0xdd, 0xf4, 0xe9, 0xf0,
	0x65, 0x6a, 0xc7, 0x6d, 0x9c, 0x8d, 0x8e, 0x65, 0x9f, 0x4d, 0x53, 0xdb, 0xc4, 0x12, 0x5a, 0x93,
	0xc3, 0x54, 0x78, 0x58, 0x1b, 0xe7, 0x61, 0xbd, 0xec, 0xe1, 0x45, 0xdd, 0x8d, 0x3f, 0xeb, 0x6e,
	0x5e, 0xd2, 0xbd, 0xf2, 0xab, 0x8a, 0x49, 0x49, 0x42, 0xf1, 0x44, 0xb6, 0x71, 0x63, 0x4d, 0x9a,
	0x4c, 0xae, 0x54, 0xab, 0x5e, 0x19, 0xd1, 0x94, 0x0f, 0x5f, 0x7f, 0x7c, 0xac, 0x10, 0xad, 0x2d,
	0x97, 0x89, 0x95, 0x53, 0x1e, 0xa0, 0x65, 0xf2, 0x1a, 0x37, 0xb6, 0xe4, 0xcc, 0xfd, 0xd7, 0xbd,
	0x8b, 0xf2, 0xde, 0x05, 0x95, 0x8c, 0xdc, 0x6b, 0xbc, 0x63, 0xce, 0xfb, 0xf4, 0x72, 0x0b, 0x57,
	0xd7, 0x41, 0x10, 0x6d, 0x24, 0x7f, 0xec, 0x54, 0x5f, 0x53, 0x43, 0x95, 0x35, 0x66, 0xc9, 0x98,
	0x1a, 0x84, 0xe1, 0x5a, 0x3a, 0x23, 0xe4, 0xee, 0x48, 0xf6, 0xf8, 0xd7, 0xa0, 0x2e, 0x5d, 0x4f,
	0xca, 0x66, 0x4b, 0x9b, 0x97, 0xe5, 0x66, 0xc8, 0xb4, 0x2c, 0xd7, 0xcf, 0xe9, 0x31, 0x79, 0x83,
	0x1b, 0x8f, 0xc1, 0x03, 0x01, 0x7f, 0x25, 0x67, 0x5e, 0xcf, 0x36, 0xa9, 0x5e, 0xac, 0x59, 0xfd,
	0x49, 0xba, 0x66, 0x0b, 0x31, 0xcb, 0x63, 0xc4, 0x3c, 0xda, 0x3c, 0x3e, 0xe9, 0xa0, 0x2f, 0x27,
	0x1d, 0xf4, 0xfd, 0xa4, 0x83, 0x3e, 0x9f, 0x76, 0xd0, 0xf1, 0x69, 0x07, 0xbd, 0x7a, 0xf8, 0xef,
	0x4b, 0xb7, 0xd4, 0xde, 0xa0, 0x21, 0x1b, 0xb8, 0xff, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xd0,
	0x6a, 0xfe, 0x52, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsedServiceServiceClient is the client API for UsedServiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsedServiceServiceClient interface {
	Create(ctx context.Context, in *UsedService, opts ...grpc.CallOption) (*UsedService, error)
	Update(ctx context.Context, in *UsedService, opts ...grpc.CallOption) (*UsedService, error)
	Get(ctx context.Context, in *OneUsedServiceRequest, opts ...grpc.CallOption) (*UsedService, error)
	List(ctx context.Context, in *ListUsedServiceRequest, opts ...grpc.CallOption) (*ListUsedServiceResponse, error)
	Delete(ctx context.Context, in *OneUsedServiceRequest, opts ...grpc.CallOption) (*types.Empty, error)
}

type usedServiceServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsedServiceServiceClient(cc *grpc.ClientConn) UsedServiceServiceClient {
	return &usedServiceServiceClient{cc}
}

func (c *usedServiceServiceClient) Create(ctx context.Context, in *UsedService, opts ...grpc.CallOption) (*UsedService, error) {
	out := new(UsedService)
	err := c.cc.Invoke(ctx, "/usedservice.UsedServiceService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usedServiceServiceClient) Update(ctx context.Context, in *UsedService, opts ...grpc.CallOption) (*UsedService, error) {
	out := new(UsedService)
	err := c.cc.Invoke(ctx, "/usedservice.UsedServiceService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usedServiceServiceClient) Get(ctx context.Context, in *OneUsedServiceRequest, opts ...grpc.CallOption) (*UsedService, error) {
	out := new(UsedService)
	err := c.cc.Invoke(ctx, "/usedservice.UsedServiceService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usedServiceServiceClient) List(ctx context.Context, in *ListUsedServiceRequest, opts ...grpc.CallOption) (*ListUsedServiceResponse, error) {
	out := new(ListUsedServiceResponse)
	err := c.cc.Invoke(ctx, "/usedservice.UsedServiceService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usedServiceServiceClient) Delete(ctx context.Context, in *OneUsedServiceRequest, opts ...grpc.CallOption) (*types.Empty, error) {
	out := new(types.Empty)
	err := c.cc.Invoke(ctx, "/usedservice.UsedServiceService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsedServiceServiceServer is the server API for UsedServiceService service.
type UsedServiceServiceServer interface {
	Create(context.Context, *UsedService) (*UsedService, error)
	Update(context.Context, *UsedService) (*UsedService, error)
	Get(context.Context, *OneUsedServiceRequest) (*UsedService, error)
	List(context.Context, *ListUsedServiceRequest) (*ListUsedServiceResponse, error)
	Delete(context.Context, *OneUsedServiceRequest) (*types.Empty, error)
}

// UnimplementedUsedServiceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUsedServiceServiceServer struct {
}

func (*UnimplementedUsedServiceServiceServer) Create(ctx context.Context, req *UsedService) (*UsedService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedUsedServiceServiceServer) Update(ctx context.Context, req *UsedService) (*UsedService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUsedServiceServiceServer) Get(ctx context.Context, req *OneUsedServiceRequest) (*UsedService, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedUsedServiceServiceServer) List(ctx context.Context, req *ListUsedServiceRequest) (*ListUsedServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedUsedServiceServiceServer) Delete(ctx context.Context, req *OneUsedServiceRequest) (*types.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterUsedServiceServiceServer(s *grpc.Server, srv UsedServiceServiceServer) {
	s.RegisterService(&_UsedServiceService_serviceDesc, srv)
}

func _UsedServiceService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsedService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsedServiceServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usedservice.UsedServiceService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsedServiceServiceServer).Create(ctx, req.(*UsedService))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsedServiceService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsedService)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsedServiceServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usedservice.UsedServiceService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsedServiceServiceServer).Update(ctx, req.(*UsedService))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsedServiceService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OneUsedServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsedServiceServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usedservice.UsedServiceService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsedServiceServiceServer).Get(ctx, req.(*OneUsedServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsedServiceService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsedServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsedServiceServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usedservice.UsedServiceService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsedServiceServiceServer).List(ctx, req.(*ListUsedServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsedServiceService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OneUsedServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsedServiceServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usedservice.UsedServiceService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsedServiceServiceServer).Delete(ctx, req.(*OneUsedServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsedServiceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usedservice.UsedServiceService",
	HandlerType: (*UsedServiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UsedServiceService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UsedServiceService_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UsedServiceService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _UsedServiceService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UsedServiceService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usedservice/usedservice.proto",
}

func (m *UsedService) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UsedService) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UsedService) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.UpdatedAt) > 0 {
		i -= len(m.UpdatedAt)
		copy(dAtA[i:], m.UpdatedAt)
		i = encodeVarintUsedservice(dAtA, i, uint64(len(m.UpdatedAt)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xaa
	}
	if len(m.CreatedAt) > 0 {
		i -= len(m.CreatedAt)
		copy(dAtA[i:], m.CreatedAt)
		i = encodeVarintUsedservice(dAtA, i, uint64(len(m.CreatedAt)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.Service != nil {
		{
			size, err := m.Service.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintUsedservice(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if len(m.BookedRoomId) > 0 {
		i -= len(m.BookedRoomId)
		copy(dAtA[i:], m.BookedRoomId)
		i = encodeVarintUsedservice(dAtA, i, uint64(len(m.BookedRoomId)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.ServiceId) > 0 {
		i -= len(m.ServiceId)
		copy(dAtA[i:], m.ServiceId)
		i = encodeVarintUsedservice(dAtA, i, uint64(len(m.ServiceId)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Price != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.Price))))
		i--
		dAtA[i] = 0x25
	}
	if m.TotalAmount != 0 {
		i -= 4
		encoding_binary.LittleEndian.PutUint32(dAtA[i:], uint32(math.Float32bits(float32(m.TotalAmount))))
		i--
		dAtA[i] = 0x1d
	}
	if m.Quantity != 0 {
		i = encodeVarintUsedservice(dAtA, i, uint64(m.Quantity))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintUsedservice(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OneUsedServiceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OneUsedServiceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OneUsedServiceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintUsedservice(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ListUsedServiceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListUsedServiceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListUsedServiceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.SearchValue) > 0 {
		i -= len(m.SearchValue)
		copy(dAtA[i:], m.SearchValue)
		i = encodeVarintUsedservice(dAtA, i, uint64(len(m.SearchValue)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.SearchField) > 0 {
		i -= len(m.SearchField)
		copy(dAtA[i:], m.SearchField)
		i = encodeVarintUsedservice(dAtA, i, uint64(len(m.SearchField)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CreatedAtMax) > 0 {
		i -= len(m.CreatedAtMax)
		copy(dAtA[i:], m.CreatedAtMax)
		i = encodeVarintUsedservice(dAtA, i, uint64(len(m.CreatedAtMax)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CreatedAtMin) > 0 {
		i -= len(m.CreatedAtMin)
		copy(dAtA[i:], m.CreatedAtMin)
		i = encodeVarintUsedservice(dAtA, i, uint64(len(m.CreatedAtMin)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Limit != 0 {
		i = encodeVarintUsedservice(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x20
	}
	if m.Page != 0 {
		i = encodeVarintUsedservice(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x18
	}
	return len(dAtA) - i, nil
}

func (m *ListUsedServiceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListUsedServiceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListUsedServiceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.SearchValue) > 0 {
		i -= len(m.SearchValue)
		copy(dAtA[i:], m.SearchValue)
		i = encodeVarintUsedservice(dAtA, i, uint64(len(m.SearchValue)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SearchField) > 0 {
		i -= len(m.SearchField)
		copy(dAtA[i:], m.SearchField)
		i = encodeVarintUsedservice(dAtA, i, uint64(len(m.SearchField)))
		i--
		dAtA[i] = 0x32
	}
	if m.Limit != 0 {
		i = encodeVarintUsedservice(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x28
	}
	if m.Page != 0 {
		i = encodeVarintUsedservice(dAtA, i, uint64(m.Page))
		i--
		dAtA[i] = 0x20
	}
	if m.TotalCount != 0 {
		i = encodeVarintUsedservice(dAtA, i, uint64(m.TotalCount))
		i--
		dAtA[i] = 0x18
	}
	if m.MaxPage != 0 {
		i = encodeVarintUsedservice(dAtA, i, uint64(m.MaxPage))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintUsedservice(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintUsedservice(dAtA []byte, offset int, v uint64) int {
	offset -= sovUsedservice(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *UsedService) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovUsedservice(uint64(l))
	}
	if m.Quantity != 0 {
		n += 1 + sovUsedservice(uint64(m.Quantity))
	}
	if m.TotalAmount != 0 {
		n += 5
	}
	if m.Price != 0 {
		n += 5
	}
	l = len(m.ServiceId)
	if l > 0 {
		n += 1 + l + sovUsedservice(uint64(l))
	}
	l = len(m.BookedRoomId)
	if l > 0 {
		n += 1 + l + sovUsedservice(uint64(l))
	}
	if m.Service != nil {
		l = m.Service.Size()
		n += 1 + l + sovUsedservice(uint64(l))
	}
	l = len(m.CreatedAt)
	if l > 0 {
		n += 2 + l + sovUsedservice(uint64(l))
	}
	l = len(m.UpdatedAt)
	if l > 0 {
		n += 2 + l + sovUsedservice(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *OneUsedServiceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovUsedservice(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListUsedServiceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Page != 0 {
		n += 1 + sovUsedservice(uint64(m.Page))
	}
	if m.Limit != 0 {
		n += 1 + sovUsedservice(uint64(m.Limit))
	}
	l = len(m.CreatedAtMin)
	if l > 0 {
		n += 1 + l + sovUsedservice(uint64(l))
	}
	l = len(m.CreatedAtMax)
	if l > 0 {
		n += 1 + l + sovUsedservice(uint64(l))
	}
	l = len(m.SearchField)
	if l > 0 {
		n += 1 + l + sovUsedservice(uint64(l))
	}
	l = len(m.SearchValue)
	if l > 0 {
		n += 1 + l + sovUsedservice(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListUsedServiceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovUsedservice(uint64(l))
		}
	}
	if m.MaxPage != 0 {
		n += 1 + sovUsedservice(uint64(m.MaxPage))
	}
	if m.TotalCount != 0 {
		n += 1 + sovUsedservice(uint64(m.TotalCount))
	}
	if m.Page != 0 {
		n += 1 + sovUsedservice(uint64(m.Page))
	}
	if m.Limit != 0 {
		n += 1 + sovUsedservice(uint64(m.Limit))
	}
	l = len(m.SearchField)
	if l > 0 {
		n += 1 + l + sovUsedservice(uint64(l))
	}
	l = len(m.SearchValue)
	if l > 0 {
		n += 1 + l + sovUsedservice(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovUsedservice(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozUsedservice(x uint64) (n int) {
	return sovUsedservice(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *UsedService) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsedservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UsedService: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UsedService: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			m.Quantity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quantity |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalAmount", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.TotalAmount = float32(math.Float32frombits(v))
		case 4:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint32(encoding_binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
			m.Price = float32(math.Float32frombits(v))
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ServiceId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ServiceId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BookedRoomId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BookedRoomId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Service", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Service == nil {
				m.Service = &service.Service{}
			}
			if err := m.Service.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 21:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpdatedAt = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsedservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUsedservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OneUsedServiceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsedservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OneUsedServiceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OneUsedServiceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsedservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUsedservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListUsedServiceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsedservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListUsedServiceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListUsedServiceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtMin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAtMin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtMax", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedAtMax = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SearchField", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SearchField = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SearchValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SearchValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsedservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUsedservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListUsedServiceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowUsedservice
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListUsedServiceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListUsedServiceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, &UsedService{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxPage", wireType)
			}
			m.MaxPage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxPage |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalCount", wireType)
			}
			m.TotalCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Page", wireType)
			}
			m.Page = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Page |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SearchField", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SearchField = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SearchValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthUsedservice
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthUsedservice
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SearchValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipUsedservice(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthUsedservice
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipUsedservice(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowUsedservice
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowUsedservice
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthUsedservice
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupUsedservice
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthUsedservice
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthUsedservice        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowUsedservice          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupUsedservice = fmt.Errorf("proto: unexpected end of group")
)
