// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: room/room.proto

package room

import (
	fmt "fmt"
	math "math"
	proto "github.com/gogo/protobuf/proto"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	_ "github.com/gogo/protobuf/types"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/nekizz/final-project/backend/go-pbtype/amenity"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Room) Validate() error {
	for _, item := range this.ListAmenity {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("ListAmenity", err)
			}
		}
	}
	return nil
}
func (this *CheckingRoomRequest) Validate() error {
	return nil
}
func (this *OneRoomRequest) Validate() error {
	return nil
}
func (this *ListRoomRequest) Validate() error {
	return nil
}
func (this *ListRoomResponse) Validate() error {
	for _, item := range this.Items {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Items", err)
			}
		}
	}
	return nil
}
func (this *ListRoomByBookedRoomRequest) Validate() error {
	return nil
}
func (this *ListRoomByBookedRoomResponse) Validate() error {
	for _, item := range this.Items {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Items", err)
			}
		}
	}
	return nil
}
