// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: authentication/authentication.proto

package authentication

import (
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	golang_proto "github.com/golang/protobuf/proto"
	_ "github.com/nekizz/final-project/backend/go-pbtype/notification"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Authentication) Validate() error {
	return nil
}
func (this *AuthenticationResponse) Validate() error {
	return nil
}
func (this *CheckingOtpExpirationRequest) Validate() error {
	return nil
}
